### ISSUE TITLE
fabsf vs fabs

### ISSUE THREAD

**Issue by stonedauwg** [carlj/CJAMacros#15]
For the line:

#define SYSTEM_VERSION_EQUAL_TO(_gVersion)    ( fabsf(NSFoundationVersionNumber - _gVersion) < DBL_EPSILON )

Shouldn't the fabsf be fabs since the comparison is to a double instead of a float? I get a compiler warning about it.

**Comment by troohin** [comment]
Hi. I have same issue for now. I think this because you don't release latest version of CJAMacros (2.1.2) to the CocoaPods Specs repo. Now the latest version available through CocoaPods is 2.1.1.

**Comment by carlj** [comment]
@troohin sry my fault i forgot to push the Podspec to the CocoaPods Repo. Should be available in a few minutes.

**Comment by troohin** [comment]
It's ok now, thank you very much!
